basePath: /bms
definitions:
  board.Board:
    properties:
      baseDate:
        $ref: '#/definitions/model.BaseDate'
      boardInfo:
        $ref: '#/definitions/board.BoardInfo'
      id:
        type: integer
    type: object
  board.BoardInfo:
    properties:
      content:
        type: string
      title:
        type: string
      userId:
        type: string
    type: object
  model.BaseDate:
    properties:
      created:
        type: string
      updated:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Board Management Server Swagger
  version: "1.0"
paths:
  /board:
    post:
      consumes:
      - application/json
      description: Create Board
      parameters:
      - description: BoardCreateRequest
        in: body
        name: board
        required: true
        schema:
          $ref: '#/definitions/board.BoardInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/board.Board'
      summary: Create Board
swagger: "2.0"
